### ISSUE TITLE
Error when loading old bitfiles with new nifpga-python

### ISSUE THREAD

**Issue by mmatthe** [ni/nifpga-python#25]
Guys, it's great you finally added cluster/fixpoint support! Unfortunately, the changes break compatibility to older biltfiles:

Consider this bitfile (created with npfpga-v17): https://raw.githubusercontent.com/ewine-project/Flexible-GFDM-PHY/master/Builds/USRP-Bitfile-0026.lvbitx

with recent nifpga-python (pip install nifpga) one gets this error:

```
$ python -c "import nifpga; nifpga.Bitfile('USRP-Bitfile-0026.lvbitx')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/e2/lib/python3.7/site-packages/nifpga/bitfile.py", line 36, in __init__
    reg = Register(reg_xml)
  File "/tmp/e2/lib/python3.7/site-packages/nifpga/bitfile.py", line 598, in __init__
    self._type = _parse_type(list(datatype)[0])
  File "/tmp/e2/lib/python3.7/site-packages/nifpga/bitfile.py", line 114, in _parse_type
    return _FXP(name, type_xml)
  File "/tmp/e2/lib/python3.7/site-packages/nifpga/bitfile.py", line 384, in __init__
    self._signed = True if type_xml.find("Signed").text.lower() == 'true' else False
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by badgraphicsghost** [comment]
Thanks for the bug report!

I've added a pull request that makes the Python API ignore registers and FIFOs that don't contain all of the metadata in the XML.  So your bitfile will be usable again, but your session won't have access to any FXP types.  If you are able to recompile your bitfile in newer versions of LabVIEW Communications (>=2.1) they will output the correct XML such that they are usable from the Python API.
