### ISSUE TITLE
InvalidResourceNameError from an lvbitx compiled from cloud compile service

### ISSUE THREAD

**Issue by ninosarmiento** [ni/nifpga-python#30]
How do I resolve this issue on InvalidResourceNameError?

-------------------
with Session(bitfile="c:\\temp\\test.lvbitx", resource="RIO0") as session:
    session.reset()
    session.run()
    my_indicator = session.registers['Frequency']
    data = my_indicator.read()
    print(data)
---------------	

	
InvalidResourceNameError: Error: InvalidResourceName (-63192) when calling 'NiFpgaDll_Open' with arguments:
	bitfile path: b'c:\\temp\\test.lvbitx'
	signature: b'047C388B436FDC3224D0A45B4CA35251'
	resource: b'RIO0'
	attribute: 0x0
	session: 0x0

**Comment by badgraphicsghost** [comment]
InvalidResourceName means that your resource "RIO0" didn't correspond to any device on your machine.  I would recommend opening MAX and double checking the name of your RIO Device.
