### ISSUE TITLE
Error: InvalidResourceName (-63192) when calling 'NiFpgaDll_Open

### ISSUE THREAD

**Issue by manishkumaretn** [ni/nifpga-python#43]
Hi. I am getting following error while opening the session with NIFPGA:

nifpga.status.InvalidResourceNameError: Error: InvalidResourceName (-63192) when calling 'NiFpgaDll_Open' with arguments:
	bitfile path: b'C:\\Eclipse_WS\\NIDAQMX\\SquareNumber_FPGATarget_Test1_okVPBnie6P8.lvbitx'
	signature: b'D9DA997A0C0155146DD77DAEC8CC6F9
![NI-MAXProperty](https://github.com/ni/nifpga-python/assets/140724148/d511ee94-3be4-431d-9033-b3c24356af43)
![TargetProperty](https://github.com/ni/nifpga-python/assets/140724148/b89891a8-574b-47ad-83cc-f50430ed8382)
7'
	resource: b'RIO1'
	attribute: 0x0
	session: 0x0

I cross checked the Resource name in NI-MAX and same name is updated in Target file as well. Pl find attached image of MAX and Project properties.

Test environment details:
3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
Package    Version
---------- -------
future     0.18.3
nidaqmx    0.5.7
nifpga     22.0.0
numpy      1.19.5
pip        21.3.1
setuptools 28.8.0
six        1.16.0

Thanks,
Manish

**Comment by strainmike** [comment]
Since you are talking to a device on a remote PXI target, you need to change your resource name from "RIO1"to "rio://192.168.1.1/RIO1".  That will tell that tell NiFpga to open a remote session to RIO1 on 192.168.1.1 instead of opening a session to a device named RIO1 on your windows machine.

**Comment by manishkumaretn** [comment]
Thanks for your response. It is working now.
