### ISSUE TITLE
niswitch.errors.DriverError: -1074118644: No legacy device supports the specified topology.

### ISSUE THREAD

**Issue by manishkumaretn** [ni/nifpga-python#44]
Hi,
I am getting following error while trying to open niswitch session in python.
niswitch.errors.DriverError: -1074118644: No legacy device supports the specified topology.  Use a different topology, or configure the device under DAQmx and use the DAQmx resource descriptor.

Python code:
import niswitch
resource = "visa://192.168.1.1/PXI8::8::INSTR" 
topology1 = "2566/16-SPDT"

with niswitch.Session(resource, topology1) as session:
    session.connect(channel1='k0', channel2='com0')

Test environment details:
3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
Package    Version
---------- -------
future     0.18.3
hightime   0.2.1
nidaqmx    0.5.7
nifpga     22.0.0
niswitch   1.4.5
numpy      1.19.5
pip        21.3.1
setuptools 28.8.0
six        1.16.0

**Comment by strainmike** [comment]
I think you want to post this at [https://github.com/ni/nimi-python](https://github.com/ni/nimi-python) instead.  This page is for the nifpga library and your error is coming out of niswitch.
