### ISSUE TITLE
Board compatibility

### ISSUE THREAD

**Issue by galla15** [ni/nifpga-python#45]
Hi, 
we are considering buying a USB 7845R for a project, and I wanted to be sure that is compatible with the "nifpga" module since I can't find any information that explicitly says it. 

Kind Regards

**Comment by strainmike** [comment]
The USB-7845R is compatible.  The python API builds on the NiFpga C API, so any target compatible with the C API is also compatible with the Python API.  

I'm not sure we have a compatibility table for the C API either, but the LabVIEW FPGA Host Interface pallet is also built on the same API, so if it works, Python should work.  Almost all LabVIEW FPGA targets should be supported, the possible exceptions might be some of the more complex RF products that want you to use their API instead.
